---
- name: check bjam config
  stat: path=/home/vagrant/user-config.jam
  register: bjam_needs_upgrade

- name: check if boost tarball is already downloaded
  stat: path="{{ boost_dest }}"
  register: boost_needs_dl

- name: download boost tarball
  command: sudo {{ item }} chdir="/home/vagrant"
  with_items:
    - wget {{ boost_url }}
    - tar xf {{ boost_tarball }}
  when: not boost_needs_dl.stat.exists

- name: copy boost jamfile configuration
  template: src=user-config.jam.j2 dest="/home/vagrant/user-config.jam"
  when: not bjam_needs_upgrade.stat.exists
