---
- name: check if open-MPI already installed
  stat: path={{ openmpi_build }}/bin/mpirun
  register: openmpi_need_install

- name: checkout open-MPI repo into {{ openmpi_dir }}
  git: >
    dest="{{ openmpi_dir }}"
    repo="{{ openmpi_repo }}"
    version="{{ openmpi_version }}"
    accept_hostkey=yes

- name: be sure GNU Flex is installed
  apt: >
    pkg=flex
    state=installed

- name: install open-MPI
  command: sudo {{ item }} chdir="{{ openmpi_dir }}"
  with_items:
    - ./autogen.pl
    - ./configure --prefix="{{ openmpi_build }}"
    - make all install
  when: not openmpi_need_install.stat.exists
