---
- name: checkout open-MPI repo into {{ openmpi_dir }}
  git: >
    dest="{{ openmpi_dir }}"
    repo="{{ openmpi_repo }}"
    version="{{ openmpi_version }}"
    accept_hostkey=yes

- name: be sure GNU Flex is installed
  apt: >
    pkg=flex
    state=installed
